### ISSUE TITLE
Portfolio Plan doesn't allow to organize item vertically

### ISSUE THREAD

**Issue by lfssp** [microsoft/featuretimeline#243]
I have a plan with more than 30 items and I want to display as a prioritized view from top down, but this is not possible and I end up with priority items down the list and non-priority items on top. It leads me to be scrolling the page up/down all the time. It's really bad.

**Comment by daveatdnvgl** [comment]
Currently, Azure DevOps automatically orders Epics vertically based on available space on the timeline. However, we want to be able to decide the vertical order ourselves.

This is because we are a large organization with many teams within each project, so it would not be convenient for us to have one project per team (because then we wouldn't have the backlog for multiple teams in one project.

So to organize epics vertically in the portfolio plan would be extremely useful.
