### ISSUE TITLE
Add info icon before feature has been dragged over

### ISSUE THREAD

**Issue by cmeyertons** [microsoft/featuretimeline#48]
This is useful as it allows the user stories to be dragged first on a new feature w/o having to drag the feature first

![image](https://user-images.githubusercontent.com/19917677/46535257-6a4b1d00-c870-11e8-9f69-49d59e43e89f.png)

**Comment by petmat** [comment]
I was thinking about looking at this but can't get the app running locally. I tried `npm run dev:http` but `http://localhost:8888` gives me just this: 

![image](https://user-images.githubusercontent.com/3600035/46808517-3a6eae80-cd75-11e8-8712-4c76632c109e.png)

<details><summary>This is my console output</summary>
> feature-timeline@1.0.0 dev:http C:\github\petmat\featuretimeline
> webpack-dev-server --progress --colors --content-base ./ --port 8888

 10% building modules 2/2 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:8888/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from C:\github\petmat\featuretimeline         ⚠ ｢wdm｣: Hash: 2f45c0a3bc3efa175c00Version: webpack 4.16.1
Time: 45703ms
Built at: 2018-10-11 16:42:24
                  Asset      Size           Chunks             Chunk Names
             details.md  2.09 KiB                   [emitted]
         EpicRoadmap.js   2.4 MiB      EpicRoadmap  [emitted]  EpicRoadmap
     EpicRoadmap.js.map  2.71 MiB      EpicRoadmap  [emitted]  EpicRoadmap
 FeatureTimeline.js.map  2.81 MiB  FeatureTimeline  [emitted]  FeatureTimeline
    libs/VSS.SDK.min.js  16.5 KiB                   [emitted]
               react.js  7.05 KiB                   [emitted]
           react-dom.js  94.2 KiB                   [emitted]
   featuretimeline.html  3.24 KiB                   [emitted]
       EpicRoadmap.html  2.88 KiB                   [emitted]
     FeatureTimeline.js  2.46 MiB  FeatureTimeline  [emitted]  FeatureTimeline
images/child-rollup.png  37.9 KiB                   [emitted]
images/epic-roadmap.png  67.3 KiB                   [emitted]
     images/FT_doc1.png  74.3 KiB                   [emitted]
     images/FT_doc2.png  90.9 KiB                   [emitted]
        images/icon.png  23.4 KiB                   [emitted]
    images/main-img.png  21.9 KiB                   [emitted]
images/manual-plan1.gif   256 KiB                   [emitted]
        images/png3.gif   761 KiB                   [emitted]
Entrypoint FeatureTimeline = FeatureTimeline.js FeatureTimeline.js.map
Entrypoint EpicRoadmap = EpicRoadmap.js EpicRoadmap.js.map
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {FeatureTimeline} {EpicRoadmap} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {FeatureTimeline} {EpicRoadmap} [built]
[./node_modules/url/url.js] 22.8 KiB {FeatureTimeline} {EpicRoadmap} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8888] (webpack)-dev-server/client?http://localhost:8888 7.75 KiB {FeatureTimeline} {EpicRoadmap} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {FeatureTimeline} {EpicRoadmap} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {FeatureTimeline} {EpicRoadmap}
[built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {FeatureTimeline} {EpicRoadmap} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {FeatureTimeline} {EpicRoadmap} [built]
[./src/EpicRoadmap/EpicRoadmap.tsx] 923 bytes {EpicRoadmap} [built]
[./src/EpicRoadmap/react/Components/EpicRoadmapView.tsx] 6.99 KiB {EpicRoadmap} [built]
[./src/FeatureTimeline/FeatureTimeline.tsx] 932 bytes {FeatureTimeline} [built]
[./src/polyfill.ts] 3.91 KiB {FeatureTimeline} {EpicRoadmap} [built]
[react-dom] external "react-dom" 42 bytes {FeatureTimeline} {EpicRoadmap} [built]
[0] multi (webpack)-dev-server/client?http://localhost:8888 ./src/FeatureTimeline/FeatureTimeline.tsx 40 bytes {FeatureTimeline} [built]
[1] multi (webpack)-dev-server/client?http://localhost:8888 ./src/EpicRoadmap/EpicRoadmap.tsx 40 bytes {EpicRoadmap} [built]
    + 777 hidden modules

WARNING in ./node_modules/react-splitter-layout/lib/index.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'data:application/json;base64,"+btoa(unescape(encodeURIComponent(JSON.stringify(o))))+"': Error: Can't resolve './data:application/json;base64,"+btoa(unescape(encodeURIComponent(JSON.stringify(o))))+"' in 'C:\github\petmat\featuretimeline\node_modules\react-splitter-layout\lib'
 @ ./src/FeatureTimeline/react/Components/FeatureTimelineGrid.tsx 19:0-304:2
 @ ./src/FeatureTimeline/FeatureTimeline.tsx
 @ multi (webpack)-dev-server/client?http://localhost:8888 ./src/FeatureTimeline/FeatureTimeline.tsx
ℹ ｢wdm｣: Compiled with warnings.
</details>


Can you help me get going?

**Comment by navneet-g** [comment]
Sorry I missed this message. Please let me know if you have time for a call and I can get you upto the speed.
