### ISSUE TITLE
Child stories / pbi's from a different team projects are not shown

### ISSUE THREAD

**Issue by davesmits** [Microsoft/featuretimeline#8]
**Describe the bug**
Turn on details so it shows the releated child stories / pbi's for a feature. Then notice it doesn't show linked stories / pbi's that are coming from other team projects while I would expect it still would show those as well

**Browser**
Choose a browser
[ ] IE11
[ ] Chrome
[ ] FireFox
[ ] Safari
[x] Edge

**Version**
[x] VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

ps: I really love the progress that been made in this extension!

**Comment by navneet-g** [comment]
Thanks for reporting @davesmits ... I have marked this as an enhancement rather than a bug. For now we pull everything from the project of the Feature itself... the change is small but I need to think it through as it may impact the performance for the users who have lots of projects in their collection/account.

**Comment by navneet-g** [comment]
@davesmits can you provide more context on the scenarios where you have cross project Stories linked as Children for Features? What is the business case?

**Comment by davesmits** [comment]
we have two development teams; one team is working on more reusable product and one team on more customer specific part. We isolated these teams in own Team Projects. Product Management is happening more from the product side but need sometimes a more clear look though also for what the customer specific team is doing for specific features

**Comment by navneetg-msft** [comment]
Why did you decide to create separate team project instead of teams with different Area paths?

**Comment by davesmits** [comment]
because few components are 'customer' specific and the engine is a more generic product we build. Especially when we get more of those customer specific stuff dont want it gets too much presence on the backlog of the 'product'

and another reason is security. we have external teams doing the project development work while we do all the planning and project management

**Comment by navneetg-msft** [comment]
Thanks for the explanation. Do you use same process (WorkItem Types, States) for both the projects or are they any different? Also how do you align the teams across projects in terms of Sprints they use and start and end date for sprints.
We need to consider all these scenarios before opening up for cross project.

**Comment by davesmits** [comment]
we do use the same template (Agile); but here is the comes the complicated one; we don't use the same sprints. while the team that works on the customer specific features follow scrums with 3 weeks sprints the team that works on the product part is doing Kanban; to be able to keep some progress visualization in VSTS we mostly use a sprint per month so we see some deadlines and goals dates when we need a specific feature for the other team. But I understand the complexity how to visualize that

**Comment by navneetg-msft** [comment]
We just released an update which makes it easier to track Cross team dependencies, it is called Epic Roadmap. While working on it we looked into what it will take to support cross project, but due to possibility of process differences and area/iteration path differences it is not easy to support it.
Can you try using the same project but using Area Path permissions to control who has access to what work items?  
https://docs.microsoft.com/en-us/vsts/organizations/security/set-permissions-access-work-tracking?view=vsts
