### ISSUE TITLE
Suggestion: Add the ability to enhance features

### ISSUE THREAD

**Issue by earthling2** [Microsoft/featuretimeline#85]
On the feature timeline, add the ability to enhance features without it appearing as if the feature has been in progress from the beginning of that feature.

![feature timeline - current view for comparison](https://user-images.githubusercontent.com/47393888/52390921-1b003d80-2a58-11e9-8098-fd664024acbf.png)
![mockup - feature enhancements](https://user-images.githubusercontent.com/47393888/52390928-1dfb2e00-2a58-11e9-8f71-3d284163812e.png)

**Comment by navneet-g** [comment]
I am not able to understand form the image what is happening. Can you highlight the changes?

**Comment by neozenith** [comment]
If you look at the gravity controls row under the environmental controls epic there is a split in that feature because there are potentially no work items for it in those middle iterations.

So the feature is rendered as two pills instead of one large pill.

Another option could be to visualise one large pill but change sections of the pill to look dull/different in iterations with 0 work items.

And a final suggestion could be to use the progress bars in the Show Details option to show a per iteration progress bar.

Food for thought and thanks for an awesome extension. I have some happy stakeholders.

**Comment by navneet-g** [comment]
Thanks for the feedback... I will consider this for future release.
